name: Java CI with Gradle and MySQL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup-database:
    runs-on: ubuntu-latest
    steps:
      - name: Set up MySQL
        run: |
          docker pull mysql:8
          docker run --name mysql-db -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=bookstore -d -p 3306:3306 mysql:8
      - name: Wait for MySQL
        run: sleep 10

  build:
    needs: setup-database
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew build --no-daemon

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Unit Tests
        run: ./gradlew test --no-daemon
      - name: Integration Tests with Postman
        uses: actions/newman-run@v4
        with:
          collection: './path_to_postman_collection.json'
